services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env   
    volumes:
      - .:/app
    networks:
      - bot-network

networks:
  bot-network:
    external: true