version: "3.8"

services:
  mongodb:
    image: mongo:latest
    command: [--auth]
    restart: always
    environment:
      MONGO_INITDB_DATABASE: endor
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - bot-network

networks:
  bot-network:
    external: true

volumes:
  mongodb:
