version: "3.8"

services:
  botapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - bot-network
    volumes:
      - .:/app

networks:
  bot-network:
    external: true
